package sveltekit

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/CreativeBeastDesign/pokkum/internal/ports"
)

// VirtualInstrumentationResult holds the output of PrepareVirtualInstrumentation.
type VirtualInstrumentationResult struct {
	// VirtualPath is the absolute path to the generated instrumentation file.
	VirtualPath string

	// Code is the generated TypeScript code.
	Code string

	// Skipped indicates whether injection was skipped because an instrumentation file already exists.
	Skipped bool
}

// InstrumentationExists returns true if src/instrumentation.server.ts, .js, or .mjs exists.
func InstrumentationExists(projectDir string) bool {
	candidates := []string{
		filepath.Join(projectDir, "src", "instrumentation.server.ts"),
		filepath.Join(projectDir, "src", "instrumentation.server.js"),
		filepath.Join(projectDir, "src", "instrumentation.server.mjs"),
	}
	for _, path := range candidates {
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			return true
		}
	}
	return false
}

// GenerateInstrumentationServer generates the TypeScript code for src/instrumentation.server.ts.
func GenerateInstrumentationServer(opts ports.TelemetryOptions) string {
	sampleRate := opts.SampleRate
	if sampleRate <= 0.0 || sampleRate > 1.0 {
		sampleRate = 1.0
	}

	metricsOnlyJS := "false"
	if opts.MetricsOnly {
		metricsOnlyJS = "true"
	}

	tracesEndpoint := opts.TracesEndpoint
	if tracesEndpoint == "" {
		tracesEndpoint = "http://localhost:4318/v1/traces"
	}

	metricsEndpoint := opts.MetricsEndpoint
	if metricsEndpoint == "" {
		metricsEndpoint = "http://localhost:4318/v1/metrics"
	}

	return fmt.Sprintf(`// Generated by Pokkum OpenTelemetry Auto-Instrumentation
import { NodeSDK } from "@opentelemetry/sdk-node";
import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-proto";
import { PeriodicExportingMetricReader } from "@opentelemetry/sdk-metrics";
import { OTLPMetricExporter } from "@opentelemetry/exporter-metrics-otlp-proto";
import { ParentBasedSampler, TraceIDRatioBasedSampler, ALWAYS_OFF } from "@opentelemetry/sdk-trace-base";
import { createAddHookMessageChannel } from "import-in-the-middle";
import { register } from "node:module";

// Ensure import-in-the-middle is registered for auto-instrumentation hooks
const { registerOptions } = createAddHookMessageChannel();
register("import-in-the-middle/hook.mjs", import.meta.url, registerOptions);

const tracesEndpoint = process.env.POKKUM_OTLP_TRACES_ENDPOINT ?? %q;
const metricsEndpoint = process.env.POKKUM_OTLP_METRICS_ENDPOINT ?? %q;
const metricsOnly = (process.env.POKKUM_METRICS_ONLY === "true") || %s;

const sampleRateInput = parseFloat(process.env.POKKUM_TRACE_SAMPLE_RATE ?? "%f");
const sampleRate = isNaN(sampleRateInput) ? 1.0 : Math.max(0.0, Math.min(1.0, sampleRateInput));

// Lazy init: only start SDK if telemetry endpoints are configured
if (tracesEndpoint || metricsEndpoint) {
  const traceSampler = metricsOnly
    ? ALWAYS_OFF
    : new ParentBasedSampler({ root: new TraceIDRatioBasedSampler(sampleRate) });

  const sdk = new NodeSDK({
    serviceName: process.env.POKKUM_SERVICE_NAME ?? "pokkum-app",
    sampler: traceSampler,
    traceExporter: new OTLPTraceExporter({
      url: tracesEndpoint,
    }),
    metricReader: new PeriodicExportingMetricReader({
      exporter: new OTLPMetricExporter({
        url: metricsEndpoint,
      }),
    }),
    instrumentations: metricsOnly ? [] : [getNodeAutoInstrumentations()],
  });

  sdk.start();
}
`, tracesEndpoint, metricsEndpoint, metricsOnlyJS, sampleRate)
}

// PrepareVirtualInstrumentation checks precedence and writes a virtual instrumentation.server.ts file
// into <projectDir>/.pokkum/src/instrumentation.server.ts if no user file exists.
func PrepareVirtualInstrumentation(projectDir string, opts ports.TelemetryOptions) (*VirtualInstrumentationResult, error) {
	if InstrumentationExists(projectDir) {
		return &VirtualInstrumentationResult{
			Skipped: true,
		}, nil
	}

	code := GenerateInstrumentationServer(opts)
	pokkumSrcDir := filepath.Join(projectDir, ".pokkum", "src")
	if err := os.MkdirAll(pokkumSrcDir, 0o700); err != nil {
		return nil, fmt.Errorf("create .pokkum/src directory: %w", err)
	}

	virtualPath := filepath.Join(pokkumSrcDir, "instrumentation.server.ts")
	if err := os.WriteFile(virtualPath, []byte(code), 0o600); err != nil {
		return nil, fmt.Errorf("write virtual instrumentation.server.ts: %w", err)
	}

	return &VirtualInstrumentationResult{
		VirtualPath: virtualPath,
		Code:        code,
		Skipped:     false,
	}, nil
}
