package sveltekitutils

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/CreativeBeastDesign/pokkum/internal/ports"
)

// InstrumentationExists returns true if src/instrumentation.server.ts, .js, or .mjs exists.
//
// Used by PrepareVirtualTelemetryEntry to avoid double-initializing the OTel
// SDK: a project with its own real instrumentation.server.ts (following
// SvelteKit's native kit.experimental.instrumentation.server convention,
// with the experimental flag set in the user's own svelte.config.js) has
// already set the SDK up itself — Pokkum's compile-entrypoint wrapper must
// not also start a second one.
func InstrumentationExists(projectDir string) bool {
	candidates := []string{
		filepath.Join(projectDir, "src", "instrumentation.server.ts"),
		filepath.Join(projectDir, "src", "instrumentation.server.js"),
		filepath.Join(projectDir, "src", "instrumentation.server.mjs"),
	}
	for _, path := range candidates {
		if info, err := os.Stat(path); err == nil && !info.IsDir() {
			return true
		}
	}
	return false
}

// GenerateInstrumentationServer generates a self-contained TypeScript module
// that starts a real OpenTelemetry NodeSDK and OTLP trace exporter as a side
// effect of being imported (no exported function — the SDK starts the
// moment this module's top-level code runs). Consumed by
// PrepareVirtualTelemetryEntry as the content of the bootstrap file the
// compile entrypoint wrapper imports first, before the real application
// code.
//
// Two things this deliberately does NOT do, both confirmed by real
// `bun build --compile` + run testing this session, not assumed — this
// codebase's established discipline for exactly this class of claim (see
// mem:self_review_checklist row 17):
//
//  1. No @opentelemetry/auto-instrumentations-node (or the
//     import-in-the-middle require/import hook registration an earlier
//     version of this function used to install it): a real HTTP server +
//     client round trip through node:http, with the hook registered as
//     early as possible (via --preload, before any instrumented module
//     could have been cached), produced zero spans. Auto-instrumentation
//     packages patch Node's module loader to intercept calls, and that
//     patching does not take effect under Bun's runtime. This is a real,
//     current Bun limitation, not a Pokkum bug, and not fixable by anything
//     in this generated bootstrap. Manual span creation was verified to
//     work correctly end-to-end (SDK start, tracer.startSpan, real OTLP
//     export reaching a real collector) in the same environment — see the
//     hooks.server.ts snippet this feature's documentation provides, which
//     is consequently the ONLY way this bootstrap alone produces any real
//     spans: without it, the SDK starts and exports nothing, since nothing
//     calls it.
//  2. No OTLP metrics export (@opentelemetry/exporter-metrics-otlp-proto):
//     constructing an OTLPMetricExporter alongside NodeSDK — confirmed with
//     or without a trace exporter also present — crashes at runtime once
//     compiled ("TypeError: Cannot call a class constructor
//     OTLPExporterNodeBase without |new|"), a real Bun bundler bug
//     (`bun build --compile` produces two non-interoperable copies of the
//     shared otlp-exporter-base module in the same binary). Tracing alone
//     (this function's actual output) does not hit this, since it never
//     imports the metrics exporter package at all. Tracked as a known
//     limitation on docs/items/otel-sdk-bootstrap.md;
//     --metrics-only is honestly non-functional until this is fixed
//     upstream or worked around — the generated bootstrap warns at runtime
//     rather than silently doing nothing.
func GenerateInstrumentationServer(opts ports.TelemetryOptions) string {
	sampleRate := opts.SampleRate
	if sampleRate <= 0.0 || sampleRate > 1.0 {
		sampleRate = 1.0
	}

	metricsOnlyJS := "false"
	if opts.MetricsOnly {
		metricsOnlyJS = "true"
	}

	tracesEndpoint := opts.TracesEndpoint
	if tracesEndpoint == "" {
		tracesEndpoint = "http://localhost:4318/v1/traces"
	}

	return fmt.Sprintf(`// Generated by Pokkum OpenTelemetry SDK Bootstrap
//
// This starts a real OpenTelemetry NodeSDK and OTLP TRACE exporter only.
// Two known, real limitations — see the doc comment on
// GenerateInstrumentationServer in internal/adapters/sveltekitutils/telemetry.go
// for the full empirical investigation behind both:
//
//   - No auto-instrumentation: HTTP/framework auto-instrumentation packages
//     patch Node's module loader, and that patching does not take effect
//     under Bun. Starting this SDK with nothing calling it produces zero
//     spans. To get real, route-templated spans, add the documented
//     handle/handleError snippet to your own src/hooks.server.ts — see
//     Vocabulary.md's OpenTelemetry section. This bootstrap's SDK is what
//     that snippet's tracer.startSpan() calls actually export through.
//   - No metrics export: combining an OTLP metrics exporter with NodeSDK
//     crashes once compiled via bun build --compile (a real Bun bundler
//     bug, not a Pokkum bug). --metrics-only is not currently functional.
import { NodeSDK } from "@opentelemetry/sdk-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-proto";
import { ParentBasedSampler, TraceIdRatioBasedSampler } from "@opentelemetry/sdk-trace-base";

const tracesEndpoint = process.env.POKKUM_OTLP_TRACES_ENDPOINT ?? %q;
const metricsOnly = (process.env.POKKUM_METRICS_ONLY === "true") || %s;

const sampleRateInput = parseFloat(process.env.POKKUM_TRACE_SAMPLE_RATE ?? "%f");
const sampleRate = isNaN(sampleRateInput) ? 1.0 : Math.max(0.0, Math.min(1.0, sampleRateInput));

if (metricsOnly) {
  console.error("[pokkum otel] --metrics-only requested, but OTLP metrics export is not currently functional under Bun (a real Bun bundler bug, not a Pokkum bug) — no metrics or traces will be exported. See Pokkum's --metrics-only documentation.");
} else if (tracesEndpoint) {
  const traceSampler = new ParentBasedSampler({ root: new TraceIdRatioBasedSampler(sampleRate) });

  const sdk = new NodeSDK({
    serviceName: process.env.POKKUM_SERVICE_NAME ?? "pokkum-app",
    sampler: traceSampler,
    traceExporter: new OTLPTraceExporter({
      url: tracesEndpoint,
    }),
  });

  sdk.start();
}
`, tracesEndpoint, metricsOnlyJS, sampleRate)
}

// VirtualTelemetryEntryResult holds the output of PrepareVirtualTelemetryEntry.
type VirtualTelemetryEntryResult struct {
	// EntrypointPath is the absolute path to the wrapper entry file to
	// compile instead of realEntrypointPath. Empty when Skipped is true.
	EntrypointPath string

	// Skipped indicates opts.Enabled was false, or the project already has
	// its own real src/instrumentation.server.ts (InstrumentationExists) —
	// in the latter case, the user's own setup is preserved untouched and
	// Pokkum does not also start a second SDK instance.
	Skipped bool
}

// PrepareVirtualTelemetryEntry is PR-5's real fix: rather than fighting
// SvelteKit's on-disk-only, no-override kit.experimental.instrumentation.server
// config loading (confirmed by reading the real vendored @sveltejs/kit
// source — load_svelte_config only ever reads <cwd>/svelte.config.js, no
// env/CLI override exists) — which would require either mutating the user's
// real svelte.config.js/src/ tree (violating the Zero-Mutation Build Sandbox
// invariant) or a much larger virtual-project-root mechanism — this wraps
// the compile-time entrypoint itself.
//
// It writes two files under <projectDir>/.pokkum/ (never the user's real
// project tree) at fixed, deterministic paths — not inside a fresh temp
// directory, so the resulting compiled binary's bytes stay reproducible
// across builds with identical inputs, matching this codebase's existing
// stub-launcher-determinism lesson (see Lessons.md):
//
//   - otel-bootstrap.ts: GenerateInstrumentationServer's self-contained SDK
//     bootstrap.
//   - telemetry-entry.ts: two static (not dynamic) side-effect imports, the
//     bootstrap first and realEntrypointPath second. ES module semantics
//     guarantee static imports are evaluated in declaration order before the
//     importing module's own code runs, so the SDK is fully started before
//     the real application code (and the HTTP server it creates) executes —
//     exactly the ordering auto-instrumentation needs to see the app's own
//     server creation. Both specifiers are static and literal so Bun's
//     bundler can properly resolve and bundle the real application code (a
//     dynamic, computed import specifier — deliberately used by the
//     Option A stub launcher for a different reason, see compileStub's doc
//     comment in bunruntime/resolver.go — would prevent that here).
//
// realEntrypointPath is the absolute path to the adapter-generated
// entrypoint (e.g. .svelte-kit/jesterkit-sveltekit/temp-server/index.ts)
// Compile would otherwise receive directly; callers should compile the
// returned EntrypointPath instead when Skipped is false.
func PrepareVirtualTelemetryEntry(projectDir, realEntrypointPath string, opts ports.TelemetryOptions) (*VirtualTelemetryEntryResult, error) {
	if !opts.Enabled || InstrumentationExists(projectDir) {
		return &VirtualTelemetryEntryResult{Skipped: true}, nil
	}

	pokkumDir := filepath.Join(projectDir, ".pokkum")
	if err := os.MkdirAll(pokkumDir, 0o700); err != nil {
		return nil, fmt.Errorf("create .pokkum directory: %w", err)
	}

	bootstrapPath := filepath.Join(pokkumDir, "otel-bootstrap.ts")
	if err := os.WriteFile(bootstrapPath, []byte(GenerateInstrumentationServer(opts)), 0o600); err != nil {
		return nil, fmt.Errorf("write virtual otel-bootstrap.ts: %w", err)
	}

	entryPath := filepath.Join(pokkumDir, "telemetry-entry.ts")
	entryCode := fmt.Sprintf(
		"// Generated by Pokkum OpenTelemetry Auto-Instrumentation — wraps the real compile entrypoint\nimport \"./otel-bootstrap.ts\";\nimport %q;\n",
		filepath.ToSlash(realEntrypointPath),
	)
	if err := os.WriteFile(entryPath, []byte(entryCode), 0o600); err != nil {
		return nil, fmt.Errorf("write virtual telemetry-entry.ts: %w", err)
	}

	return &VirtualTelemetryEntryResult{EntrypointPath: entryPath}, nil
}

// LayeredTelemetryBootstrapResult holds the output of
// PrepareLayeredTelemetryBootstrap.
type LayeredTelemetryBootstrapResult struct {
	// PreloadRelPath is the bootstrap file's path relative to outputDir
	// (e.g. "otel-bootstrap.ts") — the caller packages outputDir as-is, so
	// this relative path is what ends up sitting next to the real
	// entrypoint inside the image (e.g. /app/server/otel-bootstrap.ts).
	// Empty when Skipped is true.
	PreloadRelPath string

	// Skipped indicates opts.Enabled was false, or the project already has
	// its own real src/instrumentation.server.ts (InstrumentationExists) —
	// same precedence rule as PrepareVirtualTelemetryEntry.
	Skipped bool
}

// PrepareLayeredTelemetryBootstrap is the --strategy=layered counterpart to
// PrepareVirtualTelemetryEntry: --strategy=exe wraps the *compile*
// entrypoint (a source-level import, resolved by bun build --compile), but
// StrategyLayered has no compile step at all — it packages outputDir
// directly and the packaged image execs a fixed argv
// (ports.DefaultLayeredEntrypoint) against the interpreted runtime. There is
// nothing for a wrapper *import* to be compiled into.
//
// Instead, this writes otel-bootstrap.ts directly into outputDir (NOT
// .pokkum/ — unlike PrepareVirtualTelemetryEntry's wrapper files, this one
// must actually be packaged into the image, since nothing compiles it in).
// The caller is expected to have the packager insert `bun --preload
// <absolute-path>` ahead of the real entrypoint in the image's Entrypoint
// argv (see internal/adapters/packager/packager.go, which joins
// PreloadRelPath against ports.AppServerDirPrefix to build that absolute
// path) — Bun's --preload flag runs a file's side effects before the main
// entrypoint runs, which is exactly what starting the SDK first requires.
// Empirically confirmed to work with the bare `bun --preload <file> <entry>`
// invocation form (no `run` subcommand) this codebase actually uses, not
// just `bun run --preload`. The path itself MUST be absolute (or
// "./"-prefixed) — confirmed the hard way, via a failing real-run test, not
// assumed: an unprefixed relative filename (e.g. "otel-bootstrap.ts") makes
// Bun try to resolve it as an npm package specifier ("error: preload not
// found") rather than a local file. This is why the caller builds an
// absolute in-container path rather than passing PreloadRelPath through
// unmodified.
//
// Writing into outputDir (SvelteKit/adapter-node's own generated build
// output, e.g. <projectDir>/build) rather than the user's real project tree
// does NOT violate the Zero-Mutation Build Sandbox invariant — that
// invariant protects user-*authored* source files, not the adapter's own
// generated output, which this codebase already writes/patches today (see
// patchPrerenderedHandler in internal/adapters/bunexec/prerendered_patch.go,
// which modifies build/handler.js for the same strategy).
func PrepareLayeredTelemetryBootstrap(projectDir, outputDir string, opts ports.TelemetryOptions) (*LayeredTelemetryBootstrapResult, error) {
	if !opts.Enabled || InstrumentationExists(projectDir) {
		return &LayeredTelemetryBootstrapResult{Skipped: true}, nil
	}

	const bootstrapFilename = "otel-bootstrap.ts"
	bootstrapPath := filepath.Join(outputDir, bootstrapFilename)
	if err := os.WriteFile(bootstrapPath, []byte(GenerateInstrumentationServer(opts)), 0o600); err != nil {
		return nil, fmt.Errorf("write layered otel-bootstrap.ts: %w", err)
	}

	return &LayeredTelemetryBootstrapResult{PreloadRelPath: bootstrapFilename}, nil
}
